[features]
seeds = false
skip-lint = false

[programs.localnet]
idlestables = "IdLeStAbLeS1111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm -C ../steward test"
