[package]
name = "idlestables"
version = "0.1.0"
description = "IdleStables core racing + horses + tracks (MVP)"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "idlestables"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
idl-build = ["anchor-lang/idl-build"]
default = []

[dependencies]
anchor-lang = "0.31.1"
